sudo: required
dist: trusty
language: node_js
node_js:
  - "0.8"
branches:
  only:
    - master
before_install:
  - sudo apt-get update
before_script:
  - npm install -g gulp
script:
  - gulp
notifications:
    slack: fouroneeight:vfxEwuSTrSyus1D2YkhN1vle