sudo: required
language: node_js
branches:
  only:
    - master
before_install:
  - sudo apt-get install autoconf libtool pkg-config nasm build-essential libpng-dev
before_script:
  - npm install -g gulp
script:
  - gulp build
notifications:
    slack: fouroneeight:vfxEwuSTrSyus1D2YkhN1vle