os: osx
sudo: required
language: node_js
node_js:
  - "node"
branches:
  only:
    - master
before_install:
  - brew update
before_script:
  - npm install -g gulp
script:
  - gulp
notifications:
    slack: fouroneeight:vfxEwuSTrSyus1D2YkhN1vle