sudo: required
dist: xenial
language: node_js
node_js:
  - "8.14.0"
branches:
  only:
    - master
before_install:
  - sudo apt-get update
before_script:
  - bash gm-install.sh
  - npm install
script:
  - gulp clean
notifications:
slack: fouroneeight:vfxEwuSTrSyus1D2YkhN1vle