sudo: required
language: node_js
branches:
  only:
    - master
before_script:
  - sudo apt-get install autoconf libtool nasm
  - npm install -g gulp
script:
  - gulp build
notifications:
    slack: fouroneeight:vfxEwuSTrSyus1D2YkhN1vle