sudo: required
dist: xenial
language: node_js
node_js:
  - "8.14.0"
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install libjpeg-dev libtiff5-dev libpng16-dev graphicsmagick
before_script:
  - npm install
script:
  - gulp convert
notifications:
  slack: fouroneeight:vfxEwuSTrSyus1D2YkhN1vle