baseURL = "https://rustledjimmies.net/"
languageCode = "en-us"
title = "Rustled Jimmies"
copyright = "Rustled Jimmies"

enableRobotsTXT = "true"
enableEmoji = "true"

[author]
  name = "Sam Pratt"
  dev = "Juan Villela"
  devEmail = "hello@juanvillela.me"

SectionPagesMenu = "main"

[permalinks]
  section = "/comic/:filename/"

[params.meta]
  keywords = "comic, webcomic, rustled jimmies"
  description = "A comic featuring plump lil dudes with cute butts."

[params]
  twitter = "_rustledjimmies"
  instagram = "rustledjimmiescomic"
  patreon = "rustledjimmiescomic"
  OpenLinksInNewWindow = true

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true

[outputs]
  home = ["html"]
  section = ["html", "jsonfeed"]

[params.google.analytics]
  trackerID = "UA-69833960-2"

[params.google.adsense]
  adClient = "ca-pub-7275536170568967"