baseURL = "https://www.rustledjimmies.net/"
languageCode = "en-us"
title = "Rustled Jimmies"
copyright = "Rustled Jimmies"

enableRobotsTXT = "true"
enableEmoji = "true"

[author]
  name = "Sam Pratt"

SectionPagesMenu = "main"

[permalinks]
  archive = "/:comic/:title/"

[params.meta]
  keywords = "comic, webcomic, rustled jimmies"
  description = "A comic featuring plump lil dudes with cute butts."

[params]
  twitter = "_rustledjimmies"
  instagram = "rustledjimmiescomic"
  patreon = "rustledjimmiescomic"
  OpenLinksInNewWindow = true

[outputs]
  home = ["html", "rss"]

[params.google.analytics]
    trackerID = "UA-69833960-2"
    
[params.google.adsense]
    adClient = "ca-pub-7275536170568967"