---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content/comic
  label: Comic
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: assets/comic
public_path: "/comic"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.47'
