---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/comic/do-you-mind.md
- content/comic/knock-knock.md
- content/comic/creation.md
- content/comic/curiosity-killed-the-cat.md
