---
label: Default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/comic/creation.md
- content/comic/cold-blooded.md
- content/comic/gather-the-knights.md
- content/comic/everything-will-work-out.md
- content/comic/man-spider.md
- content/comic/cinnamon.md
- content/comic/haunted-doll.md
- content/comic/wholesome-zombie.md
- content/comic/curiosity-killed-the-cat.md
- content/comic/thirsty.md
- content/comic/Struggle.md
- content/comic/concentration.md
- content/comic/bills-to-pay.md
